#pragma once

#include <cmath>
#include <stdexcept>

// generated by GEMINI, edited
// 1. Matrix Multiplication
template <class VectorType, class MatrixType>
MatrixType multiplyMatrices(const MatrixType& A, const MatrixType& B)
{
  int rowsA = A.rows();
  int colsA = A.cols();
  int colsB = B.cols();

  if (colsA != B.size()) {
    throw std::invalid_argument("Matrix dimensions do not match for multiplication.");
  }

  // Initialize the result matrix with zeros
  MatrixType result(rowsA, VectorType(colsB, 0.0));

  for (int i = 0; i < rowsA; ++i) {
    for (int j = 0; j < colsB; ++j) {
      for (int k = 0; k < colsA; ++k) {
        result[i][j] += A[i][k] * B[k][j];
      }
    }
  }
  return result;
}

// 2. Matrix Inversion using Gauss-Jordan Elimination
template <class VectorType, class MatrixType>
MatrixType invertMatrix(const MatrixType& matrix) {
    int n = matrix.rows();
    if (n != matrix.cols()) {
        throw std::invalid_argument("Only square matrices can be inverted.");
    }

    // Create an augmented matrix [Matrix | Identity]
    MatrixType aug(n, VectorType(2 * n, 0.0));
    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < n; ++j) {
            aug[i][j] = matrix[i][j];
        }
        aug[i][i + n] = 1.0; // Identity matrix on the right side
    }

    // Gauss-Jordan Elimination with partial pivoting
    for (int i = 0; i < n; ++i) {
        // Find the pivot
        double maxEl = std::abs(aug[i][i]);
        int maxRow = i;
        for (int k = i + 1; k < n; ++k) {
            if (std::abs(aug[k][i]) > maxEl) {
                maxEl = std::abs(aug[k][i]);
                maxRow = k;
            }
        }

        // Swap the maximum row with current row
        swap(aug[i], aug[maxRow]);

        // Check for singular matrix
        if (std::abs(aug[i][i]) < 1e-10) {
            throw std::runtime_error("Matrix is singular and cannot be inverted.");
        }

        // Make the diagonal element 1
        double pivot = aug[i][i];
        for (int j = i; j < 2 * n; ++j) {
            aug[i][j] /= pivot;
        }

        // Make other rows 0 in the current column
        for (int k = 0; k < n; ++k) {
            if (k != i) {
                double factor = aug[k][i];
                for (int j = i; j < 2 * n; ++j) {
                    aug[k][j] -= factor * aug[i][j];
                }
            }
        }
    }

    // Extract the inverted matrix from the right half of the augmented matrix
    MatrixType inverse(n, VectorType(n, 0.0));
    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < n; ++j) {
            inverse[i][j] = aug[i][j + n];
        }
    }
    return inverse;
}

// 3. Matrix Division (A / B = A * B^-1)
template <class MatrixType>
MatrixType divideMatrices(const MatrixType& A, const MatrixType& B) {
    MatrixType B_inv = invertMatrix(B);
    return multiplyMatrices(A, B_inv);
}
