if(EXISTS "/home/j4s4/Documents/dgm/advection_1d/debug/tests/test_integration[1]_tests.cmake")
  include("/home/j4s4/Documents/dgm/advection_1d/debug/tests/test_integration[1]_tests.cmake")
else()
  add_test(test_integration_NOT_BUILT test_integration_NOT_BUILT)
endif()
